-- "Kullanıcılarımızdan fotoğraflar": photos users take of a place or a district (photo/PhotoService).
-- A photo is published only after it is verified: taken near the target (EXIF GPS or the device position at
-- upload), then checked by the AI service (relevant to the place, safe, no people in focus). Only the latest
-- 10 approved photos per target are kept. The coordinates themselves are never stored, only the result.
CREATE TABLE user_photos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    -- Exactly one target: a place or a district
    place_id        BIGINT REFERENCES places (id) ON DELETE CASCADE,
    district_id     BIGINT REFERENCES districts (id) ON DELETE CASCADE,
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    reject_reason   VARCHAR(20),
    -- Random name of the stored files ("<key>.jpg", "<key>_t.jpg"); NULL once the files were deleted
    -- (rejected photos keep their row a while so the user sees why)
    file_key        VARCHAR(64),
    -- Size of the stored (re-encoded) image
    width           INT         NOT NULL,
    height          INT         NOT NULL,
    -- EXIF DateTimeOriginal, when the photo had one
    taken_at        TIMESTAMPTZ,
    -- Where the location proof came from: the photo's EXIF GPS or the device position sent with the upload
    proof           VARCHAR(10),
    -- Distance between the proof position and the place / district polygon
    distance_meters DOUBLE PRECISION,
    ai_confidence   DOUBLE PRECISION,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    reviewed_at     TIMESTAMPTZ,
    CONSTRAINT user_photos_one_target CHECK ((place_id IS NULL) <> (district_id IS NULL)),
    CONSTRAINT user_photos_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT user_photos_reject_reason CHECK (reject_reason IS NULL OR reject_reason IN
        ('TOO_SMALL', 'NOT_NEAR', 'NO_LOCATION', 'NOT_RELEVANT', 'UNSAFE', 'PEOPLE', 'UNSUPPORTED')),
    CONSTRAINT user_photos_proof CHECK (proof IS NULL OR proof IN ('EXIF', 'DEVICE'))
);

-- Collages: the latest approved photos of a place / district
CREATE INDEX idx_user_photos_place ON user_photos (place_id, status, created_at DESC) WHERE place_id IS NOT NULL;
CREATE INDEX idx_user_photos_district ON user_photos (district_id, status, created_at DESC)
    WHERE district_id IS NOT NULL;
-- "My photos"
CREATE INDEX idx_user_photos_user ON user_photos (user_id, created_at DESC);
-- Retry of photos still waiting for the AI check, cleanup of rejected ones
CREATE INDEX idx_user_photos_status ON user_photos (status, created_at);
