-- Several assistant chats per user ("Sohbetler"). Each chat has its own route: "çok yorulduk", "yağmur başladı"
-- etc. only change the route that chat planned, never another chat's route or "the latest route".
CREATE TABLE assistant_conversations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    -- NULL until the first user message (then that message, shortened) or a rename
    title           VARCHAR(120),
    -- The route this chat planned; deleting the route keeps the chat
    route_id        BIGINT       REFERENCES routes (id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_message_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- "Sohbetler": newest first
CREATE INDEX idx_assistant_conversations_user ON assistant_conversations (user_id, last_message_at DESC);

ALTER TABLE assistant_messages
    ADD COLUMN conversation_id BIGINT REFERENCES assistant_conversations (id) ON DELETE CASCADE;

-- Backfill: the single chat every user had so far becomes one conversation, linked to the last route it talked about
INSERT INTO assistant_conversations (user_id, title, route_id, created_at, updated_at, last_message_at)
SELECT m.user_id,
       'Önceki sohbet',
       (SELECT r.route_id
        FROM assistant_messages r
        WHERE r.user_id = m.user_id AND r.route_id IS NOT NULL
        ORDER BY r.created_at DESC, r.id DESC
        LIMIT 1),
       min(m.created_at),
       max(m.created_at),
       max(m.created_at)
FROM assistant_messages m
GROUP BY m.user_id;

UPDATE assistant_messages m
SET conversation_id = c.id
FROM assistant_conversations c
WHERE c.user_id = m.user_id;

ALTER TABLE assistant_messages ALTER COLUMN conversation_id SET NOT NULL;

CREATE INDEX idx_assistant_messages_conversation ON assistant_messages (conversation_id, created_at DESC);

-- Routes of a day that is over are no longer "current": RouteService / RouteExpiryJob move DRAFT/ACTIVE routes
-- dated before today (Istanbul) to EXPIRED. routes.status has no CHECK constraint, so the new value needs no DDL.
-- Existing past routes are expired here once.
UPDATE routes
SET status = 'EXPIRED'
WHERE status IN ('DRAFT', 'ACTIVE')
  AND route_date < (now() AT TIME ZONE 'Europe/Istanbul')::date;
