-- Realistic routes (planning/RoutePlanner, osm/OsmContextImporter, osm/PlaceNames, planning/InterestMatcher)

-- 1) Names: OSM name:en for English requests (the main name is name:tr when OSM has it, else name)
ALTER TABLE places ADD COLUMN name_en VARCHAR(255);

-- 2) OSM cuisine as tagged ("turkish;kebab"); interest tags (local, seafood, budget) are derived from it at import.
--    NULL = not tagged or imported before this column existed (filled on the next import of the city)
ALTER TABLE places ADD COLUMN cuisine VARCHAR(255);

-- 3) Inside a university / college / school / hospital / prison / military / industrial area (institution_areas) and
--    not a museum / sight / culture venue and without a Wikidata item: left out of route plans, recommendations and
--    popular routes (still listed, on the map, in search and on its own page)
ALTER TABLE places ADD COLUMN inside_institution BOOLEAN NOT NULL DEFAULT FALSE;

-- 4) Within ~300 m of the sea coastline (coastlines): matches the "deniz" (sea) interest
ALTER TABLE places ADD COLUMN near_sea BOOLEAN NOT NULL DEFAULT FALSE;

-- 5) The Wikidata item is an event (protest, battle, ...) and the OSM element is only a marker of it: hidden, and kept
--    hidden by later imports while the element keeps that Wikidata id (popularity/PlacePopularityService)
ALTER TABLE places ADD COLUMN not_a_place BOOLEAN NOT NULL DEFAULT FALSE;

-- Polygons of institutions per city (OSM amenity=university|college|school|hospital|prison, landuse=military|industrial,
-- military=*), replaced on every successful download of the city
CREATE TABLE institution_areas (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id    BIGINT NOT NULL REFERENCES cities (id) ON DELETE CASCADE,
    osm_id     VARCHAR(40) NOT NULL,
    kind       VARCHAR(40) NOT NULL,
    name       VARCHAR(255),
    geom       geometry(MultiPolygon, 4326) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (city_id, osm_id)
);
CREATE INDEX idx_institution_areas_geom ON institution_areas USING gist (geom);

-- The sea coastline (OSM natural=coastline ways) around each city, replaced on every successful download
CREATE TABLE coastlines (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id    BIGINT NOT NULL REFERENCES cities (id) ON DELETE CASCADE,
    osm_id     VARCHAR(40) NOT NULL,
    geom       geometry(LineString, 4326) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (city_id, osm_id)
);
-- ST_DWithin(geography) in meters uses this expression index
CREATE INDEX idx_coastlines_geog ON coastlines USING gist (CAST(geom AS geography));

-- When the city's institutions / coastline were last downloaded (NULL = never / failed)
ALTER TABLE cities
    ADD COLUMN institutions_imported_at TIMESTAMPTZ,
    ADD COLUMN coastline_imported_at    TIMESTAMPTZ;

-- Where a route starts: LOCATION (the user's position), SIGHT (a district's / city's most popular sight),
-- DISTRICT / CITY (its centre). start_label is the sight / district / city name; NULL for LOCATION
ALTER TABLE routes
    ADD COLUMN start_kind  VARCHAR(20),
    ADD COLUMN start_label VARCHAR(255);

-- Sights with a Wikidata item are checked again by the next popularity pass, which now also reads the item's
-- "instance of" (an OSM marker of an event is hidden). Their current popularity stays until then
UPDATE places SET popularity_checked_at = NULL
WHERE wikidata IS NOT NULL AND category = 'ATTRACTION' AND source = 'OSM';
