CREATE EXTENSION IF NOT EXISTS postgis;

-- ============ USERS ============

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE user_preferences (
    user_id                  BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    walking_tolerance        VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    default_party_size       INTEGER     NOT NULL DEFAULT 1,
    default_budget           INTEGER,
    interests                TEXT[]      NOT NULL DEFAULT '{}',
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============ PLACES ============

CREATE TABLE places (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(255)          NOT NULL,
    description        TEXT,
    address            VARCHAR(255),
    neighborhood       VARCHAR(100),
    location           geography(Point, 4326) NOT NULL,
    category           VARCHAR(30)           NOT NULL,
    estimated_cost     INTEGER,
    rating             DOUBLE PRECISION,
    indoor             BOOLEAN               NOT NULL DEFAULT FALSE,
    avg_visit_minutes  INTEGER,
    tags               TEXT[]                NOT NULL DEFAULT '{}',
    source             VARCHAR(50)           NOT NULL DEFAULT 'MANUAL',
    source_url         VARCHAR(500),
    last_verified_at   TIMESTAMPTZ,
    created_at         TIMESTAMPTZ           NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ           NOT NULL DEFAULT now()
);

-- Spatial index: makes ST_DWithin / nearby searches use the index instead of scanning the table
CREATE INDEX idx_places_location ON places USING GIST (location);
CREATE INDEX idx_places_category ON places (category);

-- day_of_week: 1 = Monday ... 7 = Sunday (ISO). closes_at <= opens_at means it closes after midnight.
-- A place without rows has unknown hours (e.g. parks, streets).
CREATE TABLE place_opening_hours (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id    BIGINT   NOT NULL REFERENCES places (id) ON DELETE CASCADE,
    day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    opens_at    TIME     NOT NULL,
    closes_at   TIME     NOT NULL
);

CREATE INDEX idx_opening_hours_place ON place_opening_hours (place_id);

CREATE TABLE saved_places (
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    place_id   BIGINT      NOT NULL REFERENCES places (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, place_id)
);

-- ============ ROUTES ============

CREATE TABLE routes (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title                VARCHAR(255) NOT NULL,
    route_date           DATE         NOT NULL,
    status               VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    saved                BOOLEAN      NOT NULL DEFAULT FALSE,
    start_location       geography(Point, 4326) NOT NULL,
    start_time           TIME         NOT NULL,
    end_time             TIME         NOT NULL,
    party_size           INTEGER      NOT NULL DEFAULT 1,
    budget               INTEGER,
    walking_tolerance    VARCHAR(20)  NOT NULL,
    interests            TEXT[]       NOT NULL DEFAULT '{}',
    weather_condition    VARCHAR(20),
    weather_temperature  DOUBLE PRECISION,
    weather_advice       TEXT,
    notes                TEXT[]       NOT NULL DEFAULT '{}',
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_routes_user ON routes (user_id, created_at DESC);

CREATE TABLE route_stops (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id                   BIGINT      NOT NULL REFERENCES routes (id) ON DELETE CASCADE,
    place_id                   BIGINT      NOT NULL REFERENCES places (id),
    position                   INTEGER     NOT NULL,
    stop_type                  VARCHAR(20) NOT NULL,
    planned_start              TIME        NOT NULL,
    planned_end                TIME        NOT NULL,
    distance_from_previous_m   INTEGER     NOT NULL DEFAULT 0,
    walking_minutes            INTEGER     NOT NULL DEFAULT 0,
    reasons                    TEXT[]      NOT NULL DEFAULT '{}',
    status                     VARCHAR(20) NOT NULL DEFAULT 'PLANNED'
);

CREATE INDEX idx_route_stops_route ON route_stops (route_id, position);

-- ============ ASSISTANT ============

CREATE TABLE assistant_messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    route_id   BIGINT      REFERENCES routes (id) ON DELETE SET NULL,
    role       VARCHAR(20) NOT NULL,
    content    TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_assistant_messages_user ON assistant_messages (user_id, created_at DESC);
