-- The owner's own review of places (admin area): REMOVED = gone for users (hidden, listed under the city's removed
-- places), SUSPECT = may have closed (shown with a warning, never suggested). Users report closed places; anyone
-- signed in can send feedback about the app
ALTER TABLE places ADD COLUMN review VARCHAR(20);
ALTER TABLE places ADD COLUMN reviewed_at TIMESTAMPTZ;
CREATE INDEX idx_places_review ON places (review) WHERE review IS NOT NULL;

CREATE TABLE place_reports (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id    BIGINT NOT NULL REFERENCES places (id) ON DELETE CASCADE,
    user_id     BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    reason      VARCHAR(30) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at TIMESTAMPTZ,
    UNIQUE (place_id, user_id, reason)
);
CREATE INDEX idx_place_reports_open ON place_reports (created_at) WHERE resolved_at IS NULL;

CREATE TABLE app_feedback (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT REFERENCES users (id) ON DELETE SET NULL,
    message    VARCHAR(1000) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    read_at    TIMESTAMPTZ
);
