-- Every call to the Python AI service (OpenAI): who, what for, tokens and their estimated cost in USD.
-- Only counts are stored, never the message or the photo. Shown in the admin area; the monthly sum is the
-- app's own OpenAI budget lock (AI_MONTHLY_BUDGET_USD)
CREATE TABLE ai_usage (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT REFERENCES users (id) ON DELETE SET NULL,
    kind          VARCHAR(20)    NOT NULL,
    model         VARCHAR(80),
    input_tokens  INT            NOT NULL DEFAULT 0,
    output_tokens INT            NOT NULL DEFAULT 0,
    cost_usd      NUMERIC(12, 6) NOT NULL DEFAULT 0,
    ok            BOOLEAN        NOT NULL,
    millis        INT            NOT NULL,
    created_at    TIMESTAMPTZ    NOT NULL DEFAULT now()
);
CREATE INDEX idx_ai_usage_created ON ai_usage (created_at);
CREATE INDEX idx_ai_usage_user ON ai_usage (user_id, created_at);
