-- Verified sign-in: name and surname at sign-up, the e-mail is proven with a code (at sign-up and at every
-- sign-in), and sessions stay open while used: a refresh token that expires after 7 days without use.

ALTER TABLE users ADD COLUMN first_name VARCHAR(50);
ALTER TABLE users ADD COLUMN last_name VARCHAR(50);
-- NULL = signed up but the code was never entered (cannot sign in; removed after a day)
ALTER TABLE users ADD COLUMN email_verified_at TIMESTAMPTZ;
-- Accounts from before this change keep working; their next sign-in proves the e-mail with a code anyway
UPDATE users SET email_verified_at = created_at;

-- 6-digit codes e-mailed at sign-up and sign-in (only a hash is stored)
CREATE TABLE email_codes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    purpose    VARCHAR(20)  NOT NULL,
    code_hash  VARCHAR(100) NOT NULL,
    expires_at TIMESTAMPTZ  NOT NULL,
    attempts   INTEGER      NOT NULL DEFAULT 0,
    used_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_email_codes_user ON email_codes (user_id, purpose, created_at DESC);

-- One row per signed-in device. Only a SHA-256 of the refresh token is stored. Every refresh replaces the token;
-- the previous hash is kept, so a stolen token that was already used ends the session when it comes back
CREATE TABLE user_sessions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash    VARCHAR(64) NOT NULL UNIQUE,
    previous_hash VARCHAR(64),
    replaced_at   TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at    TIMESTAMPTZ NOT NULL,
    revoked_at    TIMESTAMPTZ,
    user_agent    VARCHAR(200)
);
CREATE INDEX idx_user_sessions_user ON user_sessions (user_id);
CREATE INDEX idx_user_sessions_previous ON user_sessions (previous_hash) WHERE previous_hash IS NOT NULL;
CREATE INDEX idx_user_sessions_expires ON user_sessions (expires_at);
