-- Paid, non-renewing access passes (daily / weekly / monthly / yearly).
-- A user has access while now() is between starts_at and expires_at of an ACTIVE pass.
-- Buying again before expiry stacks: the new pass starts when the current one ends.
CREATE TABLE access_passes (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    plan           VARCHAR(20)  NOT NULL,
    provider       VARCHAR(20)  NOT NULL,
    product_id     VARCHAR(100) NOT NULL,
    -- Google Play purchase token (unique: one purchase can only unlock one pass)
    purchase_token VARCHAR(512) NOT NULL UNIQUE,
    order_id       VARCHAR(100),
    price_try      INTEGER      NOT NULL,
    starts_at      TIMESTAMPTZ  NOT NULL,
    expires_at     TIMESTAMPTZ  NOT NULL,
    status         VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_access_passes_user ON access_passes (user_id, expires_at DESC);
