-- English descriptions for tourists (Accept-Language: en). Faithful translations of the
-- Turkish texts from V2 and the V6 corrections; nothing is added that the Turkish text does not say.
-- A row is only filled when its Turkish description is still exactly the seeded one, so a place an
-- admin has since rewritten never gets an outdated translation. NULL = the app falls back to Turkish.

ALTER TABLE places ADD COLUMN description_en TEXT;

UPDATE places p SET description_en = t.description_en
FROM (VALUES
    ('Tarihi Moda İskelesi',
     'Tarihi iskele binasında İBB kütüphanesi ve Beltur kafe; deniz manzaralı.',
     'An İBB library and a Beltur café in the historic pier building, with a sea view.'),
    ('Moda Çay Bahçesi',
     'Moda burnunda deniz kenarında çay bahçesi.',
     'A seaside tea garden on the Moda headland.'),
    ('Çiya Sofrası',
     'Anadolu mutfağından yöresel yemekler.',
     'Regional dishes from Anatolian cuisine.'),
    ('Halil Lahmacun',
     'Uzun yıllardır bilinen lahmacun salonu; pazartesi kapalı.',
     'A lahmacun restaurant known for many years; closed on Mondays.'),
    ('Borsam Taşfırın',
     'Taş fırın lahmacun ve pide.',
     'Stone-oven lahmacun and pide.'),
    ('Viktor Levi Şarap Evi',
     'Bahçeli şarap evi ve restoran.',
     'A wine house and restaurant with a garden.'),
    ('Walter''s Coffee Roastery',
     'Tematik üçüncü dalga kahveci.',
     'A themed third-wave coffee shop.'),
    ('Fazıl Bey''in Türk Kahvesi',
     'Çarşı içinde klasik Türk kahvesi durağı.',
     'A classic Turkish coffee stop inside the market.'),
    ('Montag Coffee Roasters',
     'Nitelikli kahve kavurucusu.',
     'A specialty coffee roaster.'),
    ('Baylan Pastanesi',
     '1923''ten beri hizmet veren tarihi pastane.',
     'A historic patisserie serving since 1923.'),
    ('Hacı Bekir Kadıköy',
     'Lokum ve akide şekeri.',
     'Turkish delight and akide (traditional hard candy).'),
    ('Meşhur Dondurmacı Ali Usta',
     'Moda''nın bilinen dondurmacısı.',
     'Moda''s well-known ice cream shop.'),
    ('Moda Sahili',
     'Deniz kenarında yürüyüş ve gün batımı.',
     'Walks by the sea and sunsets.'),
    ('Yoğurtçu Parkı',
     'Mahalle parkı, gölgelik alanlar.',
     'A neighbourhood park with shaded areas.'),
    ('Kalamış Parkı',
     'Marina kenarında geniş park.',
     'A large park beside the marina.'),
    ('Fenerbahçe Parkı',
     'Fenerbahçe burnunda deniz kenarında geniş park.',
     'A large seaside park on the Fenerbahçe headland.'),
    ('Yeldeğirmeni Sokak Sanatı',
     'Duvar resimleriyle bilinen tarihi mahalle.',
     'A historic neighbourhood known for its murals.'),
    ('Kadıköy Boğa Heykeli',
     'Altıyol''daki simge heykel.',
     'The landmark statue at Altıyol.'),
    ('Haydarpaşa Garı',
     'Tarihi gar binası restorasyonda, içeri girilemiyor; binayı rıhtımdan ve sahilden görebilirsin.',
     'The historic station building is under restoration and cannot be entered; you can see it from the quay and the waterfront.'),
    ('Tarihi Kadıköy Çarşısı',
     'Balıkçılar, şarküteriler ve yerel dükkanlar.',
     'Fishmongers, delicatessens and local shops.'),
    ('Barış Manço Evi',
     'Barış Manço''nun müzeye dönüştürülen evi. Biletler yalnızca online satılır; resmi tatillerde kapalı.',
     'Barış Manço''s house, turned into a museum. Tickets are sold online only; closed on public holidays.'),
    ('Süreyya Operası',
     '1927 yapımı tarihi opera binası. Binayı dışarıdan görebilirsin; salon yalnızca gösteri ve konserlerde açık.',
     'A historic opera building from 1927. You can see the building from outside; the hall is open only for shows and concerts.'),
    ('Akmar Pasajı',
     'Sahaf ve plakçılarıyla bilinen pasaj; dükkanların saatleri farklı.',
     'An arcade known for its second-hand booksellers and record shops; shop hours vary.'),
    ('Surp Takavor Ermeni Kilisesi',
     'Tarihi Ermeni kilisesi. İç mekan her zaman açık olmayabilir; ziyaret saatleri doğrulanmadı.',
     'A historic Armenian church. The interior may not always be open; visiting hours have not been verified.'),
    ('Aya Efimia Rum Ortodoks Kilisesi',
     'Çarşı içindeki tarihi kilise. İç mekan her zaman açık olmayabilir; ziyaret saatleri doğrulanmadı.',
     'A historic church inside the market. The interior may not always be open; visiting hours have not been verified.'),
    ('Fenerbahçe Stadyum ve Müze Turu',
     'Kulüp müzesi stadyum turuyla gezilir. Maç günleri ve resmi tatillerde tur yapılmaz; saatleri resmi sayfadan kontrol et.',
     'The club museum is visited on the stadium tour. There are no tours on match days and public holidays; check the times on the official page.')
) AS t (name, description, description_en)
WHERE p.name = t.name AND p.description = t.description;
